name: Java Compile

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Compile Main.java
        run: |
          mkdir -p bin
          javac -d bin Main.java
          ls -l bin

      - name: Upload Main.class
        uses: actions/upload-artifact@v4
        with:
          name: compiled-class
          path: bin/Main.class
